In [1]:
def count_values(arr):
  unique_values, counts = np.unique(arr, return_counts=True)

  # Print the unique values and their frequencies
  for value, count in zip(unique_values, counts):
      print(f"{value}: {count}")

In [2]:
def split_data_balanced(X, y, test_size=0.2, random_state=None):
    # Find unique labels and their counts
    unique_labels, label_counts = np.unique(y, return_counts=True)

    # Find the minimum label count
    min_label_count = np.min(label_counts)

    # Split the data for each label, ensuring balanced classes in the test set
    X_train, X_test, y_train, y_test = [], [], [], []
    for label in unique_labels:
        # Split the data for the current label
        X_label = X[y == label]
        y_label = y[y == label]
        X_label_train, X_label_test, y_label_train, y_label_test = train_test_split(
            X_label, y_label, test_size=test_size, random_state=random_state
        )

        # Add the split data to the overall train and test sets
        X_train.append(X_label_train)
        X_test.append(X_label_test)
        y_train.append(y_label_train)
        y_test.append(y_label_test)

    # Concatenate the data from all labels
    X_train = np.concatenate(X_train)
    X_test = np.concatenate(X_test)
    y_train = np.concatenate(y_train)
    y_test = np.concatenate(y_test)

    return X_train, X_test, y_train, y_test


In [53]:
def segmantation(X,y,window_length=36 ):
      step_size=1
      # Define sliding window parameters
     # Length of each segment
      step_size = 1  # Amount of overlap between segments
      # Segment the time series data with sliding window
      segments = []
      labels = []

      for i in range(0, len(X) - window_length, step_size):
          segment = X[i:i+window_length]
          segments.append(segment)
          
          # Assign label to the segment based on the presence of anomalies
          segment_labels = y[i:i+window_length]
          if np.any(segment_labels == 1):
              label = 1  # Anomaly present
          else:
              label = 0  # No anomaly
          labels.append(label)

      # Convert segments and labels to numpy arrays
      segments = np.array(segments)
      labels = np.array(labels)
      return segments,labels

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

file_path =r"C:\Users\hp\Desktop\M2\PFE\Code\code pfe\Coud source\Code\machine learnig algorithme test\data_kick.xlsx"
df=pd.read_excel(file_path)

In [54]:
X = df[[ 'TVA (m3)', 'SPPA (kPa)', 'MFOP ((m3/s)/(m3/s))', 'GASA (mol/mol)']][0:37]
y = df['STATUS'][0:37]

In [49]:
df[df['STATUS']==1].index

Int64Index([14571, 14572, 14573, 14574, 14575, 14576, 14577, 14578, 14579,
            14580,
            ...
            53240, 53241, 53242, 53243, 53244, 53245, 53246, 53247, 53248,
            53249],
           dtype='int64', length=1238)

In [55]:
X

TVA (m3)  SPPA (kPa)  MFOP ((m3/s)/(m3/s))  GASA (mol/mol)
0       39.2   82.737088                  0.05             0.0
1       39.2   68.947573                  0.05             0.0
2       39.2   68.947573                  0.05             0.0
3       39.1   68.947573                  0.05             0.0
4       39.2   68.947573                  0.05             0.0
5       39.2   75.842330                  0.05             0.0
6       39.1   62.052816                  0.05             0.0
7       39.2   68.947573                  0.05             0.0
8       39.1   75.842330                  0.05             0.0
9       39.2   68.947573                  0.05             0.0
10      39.2   75.842330                  0.05             0.0
11      39.2   75.842330                  0.05             0.0
12      39.2   82.737088                  0.05             0.0
13      39.2   75.842330                  0.05             0.0
14      39.2   68.947573                  0.05             0.0
15      39.1   68.947573                  0.05             0.0
16      39.2   75.842330                  0.05             0.0
17      39.2   62.052816                  0.05             0.0
18      39.1   68.947573                  0.05             0.0
19      39.2   68.947573                  0.05             0.0
20      39.1   62.052816                  0.05             0.0
21      39.1   75.842330                  0.05             0.0
22      39.2   75.842330                  0.05             0.0
23      39.2   68.947573                  0.05             0.0
24      39.1   75.842330                  0.05             0.0
25      39.2   75.842330                  0.05             0.0
26      39.2   62.052816                  0.05             0.0
27      39.2   68.947573                  0.05             0.0
28      39.1   75.842330                  0.05             0.0
29      39.2   75.842330                  0.05             0.0
30      39.2   75.842330                  0.05             0.0
31      39.2   68.947573                  0.05             0.0
32      39.1   75.842330                  0.05             0.0
33      39.1   75.842330                  0.05             0.0
34      39.2   75.842330                  0.05             0.0
35      39.2   55.158058                  0.05             0.0
36      39.2   82.737088                  0.05             0.0

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# Select the columns to normalize
# Perform the min-max normalization
X= scaler.fit_transform(X)

In [57]:
window=36
segments,labels= segmantation(X,y,window_length=window )

array([3.92000000e+01, 8.27370875e+01, 5.00000000e-02, 0.00000000e+00])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = split_data_balanced(segments, labels, test_size=0.2)
print(X_train.shape,X_test.shape)
# Reshape the feature matrices for SVM
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
print(X_train.shape,X_test.shape)

(42570, 36, 4) (10644, 36, 4)
(42570, 144) (10644, 144)


In [10]:
count_values(y_test)
count_values(y_train)

0: 10354
1: 290
0: 41413
1: 1157


In [ ]:
pip install tslearn

In [11]:
from tslearn.metrics import dtw
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
knn = KNeighborsClassifier(n_neighbors=3,metric=dtw)
knn.fit(X_train, y_train)


KNeighborsClassifier(metric=<function dtw at 0x000001EB47A2EFC0>, n_neighbors=3)

In [41]:
import joblib
filename =r'C:\Users\hp\Desktop\M2\PFE\Code\code pfe\Coud source\Code\Saved models\knn_model.pkl'
joblib.dump(knn, filename)

['C:\\Users\\hp\\Desktop\\M2\\PFE\\Code\\code pfe\\Coud source\\Code\\Saved models\\knn_model.pkl']

In [43]:
loaded_model = joblib.load(filename)
predictions = loaded_model.predict(X_test[1:2])

array([0])

In [12]:

y_prd=[]

In [22]:
for i in range(len(y_test) - 1,9642 , -1): 
    y_pred = knn.predict(X_test[i-1:i])
    y_prd.append(y_pred[0])
    print(i,i-1)

10643 10642
10642 10641
10641 10640
10640 10639
10639 10638
10638 10637
10637 10636
10636 10635
10635 10634
10634 10633
10633 10632
10632 10631
10631 10630
10630 10629
10629 10628
10628 10627
10627 10626
10626 10625
10625 10624
10624 10623
10623 10622
10622 10621
10621 10620
10620 10619
10619 10618
10618 10617
10617 10616
10616 10615
10615 10614
10614 10613
10613 10612
10612 10611
10611 10610
10610 10609
10609 10608
10608 10607
10607 10606
10606 10605
10605 10604
10604 10603
10603 10602
10602 10601
10601 10600
10600 10599
10599 10598
10598 10597
10597 10596
10596 10595
10595 10594
10594 10593
10593 10592
10592 10591
10591 10590
10590 10589
10589 10588
10588 10587
10587 10586
10586 10585
10585 10584
10584 10583
10583 10582
10582 10581
10581 10580
10580 10579
10579 10578
10578 10577
10577 10576
10576 10575
10575 10574
10574 10573
10573 10572
10572 10571
10571 10570
10570 10569
10569 10568
10568 10567
10567 10566
10566 10565
10565 10564
10564 10563
10563 10562
10562 10561
10561 10560
1056

In [23]:
count_values(y_prd)

0: 794
1: 207


In [36]:
yprd=y_prd[::-1]

In [38]:
len(y_prd)

1001

In [28]:
y_actual=y_test[9643:]

In [39]:
count_values(y_actual)

0: 711
1: 290


In [37]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score,roc_auc_score

print(confusion_matrix(y_actual,yprd))
print("Accuracy:", accuracy_score(y_actual,yprd))
print("Precision:", precision_score(y_actual,yprd))
print("Recall:", recall_score(y_actual,yprd))
print("F1 Score:",f1_score(y_actual,yprd))

[[708   3]
 [ 86 204]]
Accuracy: 0.9110889110889111
Precision: 0.9855072463768116
Recall: 0.7034482758620689
F1 Score: 0.8209255533199196


In [96]:
y_pred = knn.predict(X_test)

In [98]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score,roc_auc_score

print(confusion_matrix(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall:", recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))


[[10342    12]
 [   95   195]]
Accuracy: 0.9899473881999249
Precision: 0.9420289855072463
Recall: 0.6724137931034483
F1 Score: 0.7847082494969819


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
print(X_train.shape,X_test.shape)
# Reshape the feature matrices for SVM
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
print(X_train.shape,X_test.shape)

(42594, 4) (10649, 4)
(42594, 4) (10649, 4)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from scipy.spatial.distance import cdist

def dtw_distance(ts1, ts2, window):
    """
    Computes the DTW distance between two time series with a given window.
    """
    n1, n2 = len(ts1), len(ts2)
    w = np.max([window, abs(n1 - n2)])
    dtw = np.full((n1 + 1, n2 + 1), np.inf)
    dtw[0, 0] = 0
    for i in range(1, n1 + 1):
        for j in range(np.max([1, i - w]), np.min([n2, i + w]) + 1):
            cost = abs(ts1[i - 1] - ts2[j - 1])
            dtw[i, j] = cost + np.min([dtw[i - 1, j], dtw[i, j - 1], dtw[i - 1, j - 1]])
    return dtw[-1, -1]

# Define the kNN classifier with the custom DTW distance metric
knn = KNeighborsClassifier(n_neighbors=5, metric=lambda x, y: dtw_distance(x, y, window=36))

# Fit the classifier to the training data



In [ ]:
knn.fit(X_train, y_train)



KNeighborsClassifier(metric=<function <lambda> at 0x7f2120c9b0a0>)

(10649,)

In [ ]:
# Make predictions on new data
y_pred = knn.predict(X_test)